---
kind: pipeline
name: deploy

clone:

steps:
  - name: deploy_schemas
    image: debian:stable-slim
    commands:
      - apt update && apt install -y rclone openssh-client
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - echo "$schema_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-add
      - rclone sync . $schema_host:$schema_target -v --include "*.xsd" --dry-run

trigger:
  branch:
    - master
  event:
    - push

---
kind: signature
hmac: 97a7279c3b04e431ef654a3f2d63617d5d65485ea052ee74d2d1b4f5bd9f9d7d

...
