---
kind: pipeline
name: deploy

clone:

steps:
  - name: prepare_package
    image: joomlaprojects/docker-images:packager
    commands:
      - mkdir transfer
      - mv json-schema transfer/
      - mv xsd/v3 transfer/
      - mv xsd/v4 transfer/
      - cd transfer
      - tar -cjf ../schema-packages.bz2 .

  - name: upload_package
    image: appleboy/drone-scp
    depends_on: [ prepare_package ]
    settings:
      host:
        from_secret: schema_host
      user:
        from_secret: schema_user
      key:
        from_secret: schema_key
      port: 22
      target:
        from_secret: schema_target
      source: schema-packages.bz2

  - name: extract_package
    image: appleboy/drone-ssh
    depends_on: [ upload_package ]
    settings:
      host:
        from_secret: schema_host
      user:
        from_secret: schema_user
      key:
        from_secret: schema_key
      port: 22
      script:
        - rm -rf public_html/schemas
        - mkdir public_html/schemas
        - tar jxf schema-packages.bz2 -C public_html/schemas
        - rm -f schema-packages.bz2

trigger:
  branch:
    - master
  event:
    - push

---
kind: signature
hmac: 40998be8e49a2dea5b7ae398532f2937d63079312b56ef37163f458732dfa001

...
