---
kind: pipeline
name: deploy

clone:

steps:
  - name: deploy_schemas
    image: debian:stable-slim
    environment:
      schema_key:
        from_secret: schema_key
      schema_user:
        from_secret: schema_user
      schema_host:
        from_secret: schema_host
      schema_target:
        from_secret: schema_target
    commands:
      - apt update && apt install -y rclone openssh-client
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - echo "$schema_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-add
      - rclone sync . $schema_host:$schema_target -v --include "*.xsd" --rc-user $schema_user --dry-run

trigger:
  branch:
    - master
  event:
    - push

---
kind: signature
hmac: acdbab53df4721708474e29cd27172dfb88e3f9097c96a530960f46ffdc195f5

...
