---
kind: pipeline
name: deploy

clone:

steps:
  - name: upload_schemas
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: schema_host
      user:
        from_secret: schema_user
      key:
        from_secret: schema_key
      port: 22
      target: /home/devj/public_html/schemas
      source:
        - json-schema/*
        - xsd/v3/*
        - xsd/v4/*
      rm: true

#trigger:
#  branch:
#    - master
#  event:
#    - push

---
kind: signature
hmac: 2c1f3480b1263c9e054d20583d8ffa2de2c3144835b05998b8a5fc7715c1e630

...
